[WIP] Feat/attribute schema
uor-framework/uor-client-go pull request #70
Opened 2022-08-17 20:00 UTC by jpower432

# Description

This PR adds schema publishing and validation to the CLI. It changes the commands from `build` to `build collection` and `build schema`.  Performing a build collection with a schema address will result in the schema validation against the attribute in the dataset config. This does not implement DefaultContentDeclarations, CommonAttributeMapping, or Algorithms specs. This will be done is later when those concepts for fully designed.

A couple of decisions here that may be up for discussion:
- The schema used is a generated JSON schema from user inputs. Only type checks are being completed initially, but using complex checks is possible through the library since the underlying JSON schema is exported.
- All keys specified in the schema are required in the collection attributes.
- Schema checks are only done during collection publishing, not during retrieval.

Depends on #66 

Closes #26 

# TODO
- [ ] Update docs
- [ ] Update CLI E2E

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Requires updates to the [Getting Started Guide](https://universalreference.io/docs/quick-start/)

2022-08-26 07:51 UTC, afflom commented
First of all, this PR is an incredible milestone for UOR. Thank you for your work here. 

I tested this in a few ways and found that it works as stated. I would prefer optional attributes exposed in the config, but understand that this is already a very large PR. I added an issue to track this here: https://github.com/uor-framework/uor-client-go/issues/74

LGTM

2022-08-26 14:40 UTC, afflom approved these changes

2022-08-26 23:42 UTC, sabre1041 requested changes
@jpower432 This is beyond amazing! Awesome work. 

Theres a number of enhancements (mainly around formatting in the README that I'd recommend making). However, I do not want to block this PR from getting in.

Would you be able to correct the one inline comment related to the formatting of the `SchemaConfiguration`. I'd be happy to work on the rest of the formatting as a follow up PR

2022-08-27 16:45 UTC, jpower432 commented on README.md
> +    attributeTypes:
Fixed. I also found one additional place where the formatting was not right for the `SchemaConfiguration`. That copy-paste error explains the formatting in the testing description :).

2022-08-27 17:11 UTC, sabre1041 approved these changes
LGTM

2022-08-27 17:11 UTC, merged